# Generated by Django 4.2.7 on 2023-11-24 15:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('nombre', models.CharField(max_length=128)),
                ('prefijo', models.IntegerField()),
                ('continente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.continente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pasaporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('numeropasaporte', models.CharField(max_length=64)),
                ('fechaemision', models.DateField()),
                ('fechavence', models.DateField()),
                ('observaciones', models.TextField()),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.pais')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('fechanac', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='banco',
        ),
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tarjetacredito',
            name='proveedor',
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ProveedorTarjeta',
        ),
        migrations.DeleteModel(
            name='TarjetaCredito',
        ),
        migrations.AddField(
            model_name='pasaporte',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='api.persona'),
        ),
    ]
