# Generated by Django 4.2.7 on 2023-11-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_continente_idiomaprincipal_continente_moneda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continente',
            old_name='moneda',
            new_name='abreviacion',
        ),
        migrations.RemoveField(
            model_name='continente',
            name='idiomaprincipal',
        ),
    ]
